extends:
  - "airbnb-base"
  - "plugin:vue/recommended"

parserOptions:
  ecmaVersion: 2018

env:
  browser: true
  jquery: true
  node: true

rules:
  no-console: off
  quotes: ["warn", "single", { "allowTemplateLiterals": true }]
  no-unused-vars: warn
  func-names: ["error", "as-needed"]
  object-shorthand: off
